/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTermsIndexRouteImport } from './routes/dashboard/terms/index'
import { Route as DashboardRoomsIndexRouteImport } from './routes/dashboard/rooms/index'
import { Route as DashboardHotelsIndexRouteImport } from './routes/dashboard/hotels/index'
import { Route as DashboardAmenitiesIndexRouteImport } from './routes/dashboard/amenities/index'
import { Route as DashboardTermsCreateTermRouteImport } from './routes/dashboard/terms/create-term'
import { Route as DashboardTermsIdUpdateTermRouteImport } from './routes/dashboard/terms/$id.update-term'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTermsIndexRoute = DashboardTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRoomsIndexRoute = DashboardRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHotelsIndexRoute = DashboardHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAmenitiesIndexRoute = DashboardAmenitiesIndexRouteImport.update({
  id: '/amenities/',
  path: '/amenities/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTermsCreateTermRoute =
  DashboardTermsCreateTermRouteImport.update({
    id: '/terms/create-term',
    path: '/terms/create-term',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTermsIdUpdateTermRoute =
  DashboardTermsIdUpdateTermRouteImport.update({
    id: '/terms/$id/update-term',
    path: '/terms/$id/update-term',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/terms/create-term': typeof DashboardTermsCreateTermRoute
  '/dashboard/amenities': typeof DashboardAmenitiesIndexRoute
  '/dashboard/hotels': typeof DashboardHotelsIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
  '/dashboard/terms': typeof DashboardTermsIndexRoute
  '/dashboard/terms/$id/update-term': typeof DashboardTermsIdUpdateTermRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/terms/create-term': typeof DashboardTermsCreateTermRoute
  '/dashboard/amenities': typeof DashboardAmenitiesIndexRoute
  '/dashboard/hotels': typeof DashboardHotelsIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
  '/dashboard/terms': typeof DashboardTermsIndexRoute
  '/dashboard/terms/$id/update-term': typeof DashboardTermsIdUpdateTermRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/terms/create-term': typeof DashboardTermsCreateTermRoute
  '/dashboard/amenities/': typeof DashboardAmenitiesIndexRoute
  '/dashboard/hotels/': typeof DashboardHotelsIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
  '/dashboard/terms/': typeof DashboardTermsIndexRoute
  '/dashboard/terms/$id/update-term': typeof DashboardTermsIdUpdateTermRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/terms/create-term'
    | '/dashboard/amenities'
    | '/dashboard/hotels'
    | '/dashboard/rooms'
    | '/dashboard/terms'
    | '/dashboard/terms/$id/update-term'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/terms/create-term'
    | '/dashboard/amenities'
    | '/dashboard/hotels'
    | '/dashboard/rooms'
    | '/dashboard/terms'
    | '/dashboard/terms/$id/update-term'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/terms/create-term'
    | '/dashboard/amenities/'
    | '/dashboard/hotels/'
    | '/dashboard/rooms/'
    | '/dashboard/terms/'
    | '/dashboard/terms/$id/update-term'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/terms/': {
      id: '/dashboard/terms/'
      path: '/terms'
      fullPath: '/dashboard/terms'
      preLoaderRoute: typeof DashboardTermsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rooms/': {
      id: '/dashboard/rooms/'
      path: '/rooms'
      fullPath: '/dashboard/rooms'
      preLoaderRoute: typeof DashboardRoomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/hotels/': {
      id: '/dashboard/hotels/'
      path: '/hotels'
      fullPath: '/dashboard/hotels'
      preLoaderRoute: typeof DashboardHotelsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/amenities/': {
      id: '/dashboard/amenities/'
      path: '/amenities'
      fullPath: '/dashboard/amenities'
      preLoaderRoute: typeof DashboardAmenitiesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/terms/create-term': {
      id: '/dashboard/terms/create-term'
      path: '/terms/create-term'
      fullPath: '/dashboard/terms/create-term'
      preLoaderRoute: typeof DashboardTermsCreateTermRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/terms/$id/update-term': {
      id: '/dashboard/terms/$id/update-term'
      path: '/terms/$id/update-term'
      fullPath: '/dashboard/terms/$id/update-term'
      preLoaderRoute: typeof DashboardTermsIdUpdateTermRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTermsCreateTermRoute: typeof DashboardTermsCreateTermRoute
  DashboardAmenitiesIndexRoute: typeof DashboardAmenitiesIndexRoute
  DashboardHotelsIndexRoute: typeof DashboardHotelsIndexRoute
  DashboardRoomsIndexRoute: typeof DashboardRoomsIndexRoute
  DashboardTermsIndexRoute: typeof DashboardTermsIndexRoute
  DashboardTermsIdUpdateTermRoute: typeof DashboardTermsIdUpdateTermRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTermsCreateTermRoute: DashboardTermsCreateTermRoute,
  DashboardAmenitiesIndexRoute: DashboardAmenitiesIndexRoute,
  DashboardHotelsIndexRoute: DashboardHotelsIndexRoute,
  DashboardRoomsIndexRoute: DashboardRoomsIndexRoute,
  DashboardTermsIndexRoute: DashboardTermsIndexRoute,
  DashboardTermsIdUpdateTermRoute: DashboardTermsIdUpdateTermRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
