/**
 * Intlayer configuration file documentation
 * @see https://intlayer.org/doc/concept/configuration
 */

import { type IntlayerConfig, Locales } from "intlayer";

const config: IntlayerConfig = {
	internationalization: {
		locales: [Locales.FRENCH, Locales.ENGLISH, Locales.MALAGASY_MADAGASCAR],
		defaultLocale: Locales.ENGLISH,
		requiredLocales: [Locales.FRENCH, Locales.ENGLISH],
	},
	dictionary: {
		importMode: "static",
	},
	routing: {
		/**
		 * Locale routing strategy.
		 * - "prefix-no-default": Prefix all except the default locale (e.g., /dashboard, /fr/dashboard).
		 * - "prefix-all": Prefix all locales (e.g., /en/dashboard, /fr/dashboard).
		 * - "no-prefix": No locale in the URL.
		 * - "search-params": Use ?locale=...
		 * Default: "prefix-no-default"
		 */
		mode: "prefix-no-default",
	},
	editor: {
		/**
		 * Whether the visual editor is enabled.
		 */
		enabled: false,

		/**
		 * URL of your application for origin validation.
		 */
		applicationURL: "http://localhost:3001",
	},
	content: {
		watch: true,
	},
	compiler: {
		enabled: true,

		/**
		 * Defines the output files path for autogenerated content (compiler / autofill / extract)
		 *
		 * - `./` paths are resolved relative to the component directory.
		 * - `/` paths are resolved relative to the project root (`baseDir`).
		 *
		 * - Including the `{{locale}}` variable in the path will trigger the generation of separate dictionaries per locale.
		 *
		 * Example:
		 * ```ts
		 * {
		 *   // Create Multilingual .content.ts files close to the component
		 *   output: ({ fileName, extension }) => `./${fileName}${extension}`,
		 * }
		 * ```
		 *
		 * ```ts
		 * {
		 *   // Create centralize per-locale JSON at the root of the project
		 *   output: ({ key, locale }) => `/locales/${locale}/${key}.content.json`,
		 * }
		 * ```
		 */
		output: ({ fileName }) => `./${fileName}.content.ts`,
		dictionaryKeyPrefix: "comp-",
		/**
		 * Indicates if the components should be saved after being transformed.
		 * That way, the compiler can be run only once to transform the app, and then it can be removed.
		 */
		saveComponents: false,
	},
};

export default config;
