/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/_legal/terms-of-service'
import { Route as LegalTermsAndConditionsOfSaleRouteImport } from './routes/_legal/terms-and-conditions-of-sale'
import { Route as CompanyContactRouteImport } from './routes/_company/contact'
import { Route as CompanyAboutRouteImport } from './routes/_company/about'
import { Route as AppHotelsIndexRouteImport } from './routes/_app/hotels/index'
import { Route as AppHotelIdIndexRouteImport } from './routes/_app/$hotelId/index'
import { Route as AppHotelIdRoomsIndexRouteImport } from './routes/_app/$hotelId/rooms/index'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalTermsAndConditionsOfSaleRoute =
  LegalTermsAndConditionsOfSaleRouteImport.update({
    id: '/terms-and-conditions-of-sale',
    path: '/terms-and-conditions-of-sale',
    getParentRoute: () => LegalRouteRoute,
  } as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/_company/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/_company/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHotelsIndexRoute = AppHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdIndexRoute = AppHotelIdIndexRouteImport.update({
  id: '/$hotelId/',
  path: '/$hotelId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdRoomsIndexRoute = AppHotelIdRoomsIndexRouteImport.update({
  id: '/$hotelId/rooms/',
  path: '/$hotelId/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/about': typeof CompanyAboutRoute
  '/contact': typeof CompanyContactRoute
  '/terms-and-conditions-of-sale': typeof LegalTermsAndConditionsOfSaleRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
  '/login/': typeof LoginIndexRoute
  '/$hotelId/': typeof AppHotelIdIndexRoute
  '/hotels/': typeof AppHotelsIndexRoute
  '/$hotelId/rooms/': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof CompanyAboutRoute
  '/contact': typeof CompanyContactRoute
  '/terms-and-conditions-of-sale': typeof LegalTermsAndConditionsOfSaleRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
  '/login': typeof LoginIndexRoute
  '/$hotelId': typeof AppHotelIdIndexRoute
  '/hotels': typeof AppHotelsIndexRoute
  '/$hotelId/rooms': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_legal': typeof LegalRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/_company/about': typeof CompanyAboutRoute
  '/_company/contact': typeof CompanyContactRoute
  '/_legal/terms-and-conditions-of-sale': typeof LegalTermsAndConditionsOfSaleRoute
  '/_legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/$hotelId/': typeof AppHotelIdIndexRoute
  '/_app/hotels/': typeof AppHotelsIndexRoute
  '/_app/$hotelId/rooms/': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/contact'
    | '/terms-and-conditions-of-sale'
    | '/terms-of-service'
    | '/login/'
    | '/$hotelId/'
    | '/hotels/'
    | '/$hotelId/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/terms-and-conditions-of-sale'
    | '/terms-of-service'
    | '/login'
    | '/$hotelId'
    | '/hotels'
    | '/$hotelId/rooms'
  id:
    | '__root__'
    | '/_app'
    | '/_legal'
    | '/login'
    | '/_company/about'
    | '/_company/contact'
    | '/_legal/terms-and-conditions-of-sale'
    | '/_legal/terms-of-service'
    | '/_app/'
    | '/login/'
    | '/_app/$hotelId/'
    | '/_app/hotels/'
    | '/_app/$hotelId/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyContactRoute: typeof CompanyContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_legal/terms-of-service': {
      id: '/_legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_legal/terms-and-conditions-of-sale': {
      id: '/_legal/terms-and-conditions-of-sale'
      path: '/terms-and-conditions-of-sale'
      fullPath: '/terms-and-conditions-of-sale'
      preLoaderRoute: typeof LegalTermsAndConditionsOfSaleRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_company/contact': {
      id: '/_company/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company/about': {
      id: '/_company/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hotels/': {
      id: '/_app/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AppHotelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/': {
      id: '/_app/$hotelId/'
      path: '/$hotelId'
      fullPath: '/$hotelId/'
      preLoaderRoute: typeof AppHotelIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/rooms/': {
      id: '/_app/$hotelId/rooms/'
      path: '/$hotelId/rooms'
      fullPath: '/$hotelId/rooms/'
      preLoaderRoute: typeof AppHotelIdRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppHotelIdIndexRoute: typeof AppHotelIdIndexRoute
  AppHotelsIndexRoute: typeof AppHotelsIndexRoute
  AppHotelIdRoomsIndexRoute: typeof AppHotelIdRoomsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppHotelIdIndexRoute: AppHotelIdIndexRoute,
  AppHotelsIndexRoute: AppHotelsIndexRoute,
  AppHotelIdRoomsIndexRoute: AppHotelIdRoomsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalTermsAndConditionsOfSaleRoute: typeof LegalTermsAndConditionsOfSaleRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalTermsAndConditionsOfSaleRoute: LegalTermsAndConditionsOfSaleRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyContactRoute: CompanyContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
