/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHotelsIndexRouteImport } from './routes/_app/hotels/index'
import { Route as AppHotelIdIndexRouteImport } from './routes/_app/$hotelId/index'
import { Route as AppHotelIdRoomsIndexRouteImport } from './routes/_app/$hotelId/rooms/index'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelsIndexRoute = AppHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdIndexRoute = AppHotelIdIndexRouteImport.update({
  id: '/$hotelId/',
  path: '/$hotelId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdRoomsIndexRoute = AppHotelIdRoomsIndexRouteImport.update({
  id: '/$hotelId/rooms/',
  path: '/$hotelId/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/$hotelId/': typeof AppHotelIdIndexRoute
  '/hotels/': typeof AppHotelsIndexRoute
  '/$hotelId/rooms/': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/$hotelId': typeof AppHotelIdIndexRoute
  '/hotels': typeof AppHotelsIndexRoute
  '/$hotelId/rooms': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/$hotelId/': typeof AppHotelIdIndexRoute
  '/_app/hotels/': typeof AppHotelsIndexRoute
  '/_app/$hotelId/rooms/': typeof AppHotelIdRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login/'
    | '/$hotelId/'
    | '/hotels/'
    | '/$hotelId/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$hotelId' | '/hotels' | '/$hotelId/rooms'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/login/'
    | '/_app/$hotelId/'
    | '/_app/hotels/'
    | '/_app/$hotelId/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hotels/': {
      id: '/_app/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AppHotelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/': {
      id: '/_app/$hotelId/'
      path: '/$hotelId'
      fullPath: '/$hotelId/'
      preLoaderRoute: typeof AppHotelIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/rooms/': {
      id: '/_app/$hotelId/rooms/'
      path: '/$hotelId/rooms'
      fullPath: '/$hotelId/rooms/'
      preLoaderRoute: typeof AppHotelIdRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppHotelIdIndexRoute: typeof AppHotelIdIndexRoute
  AppHotelsIndexRoute: typeof AppHotelsIndexRoute
  AppHotelIdRoomsIndexRoute: typeof AppHotelIdRoomsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppHotelIdIndexRoute: AppHotelIdIndexRoute,
  AppHotelsIndexRoute: AppHotelsIndexRoute,
  AppHotelIdRoomsIndexRoute: AppHotelIdRoomsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
