/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHotelIdIndexRouteImport } from './routes/_app/$hotelId/index'
import { Route as AppHotelIdRoomsPageRouteImport } from './routes/_app/$hotelId/rooms/page'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdIndexRoute = AppHotelIdIndexRouteImport.update({
  id: '/$hotelId/',
  path: '/$hotelId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelIdRoomsPageRoute = AppHotelIdRoomsPageRouteImport.update({
  id: '/$hotelId/rooms/page',
  path: '/$hotelId/rooms/page',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/$hotelId/': typeof AppHotelIdIndexRoute
  '/$hotelId/rooms/page': typeof AppHotelIdRoomsPageRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/$hotelId': typeof AppHotelIdIndexRoute
  '/$hotelId/rooms/page': typeof AppHotelIdRoomsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/$hotelId/': typeof AppHotelIdIndexRoute
  '/_app/$hotelId/rooms/page': typeof AppHotelIdRoomsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/login/' | '/$hotelId/' | '/$hotelId/rooms/page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$hotelId' | '/$hotelId/rooms/page'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/login/'
    | '/_app/$hotelId/'
    | '/_app/$hotelId/rooms/page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/': {
      id: '/_app/$hotelId/'
      path: '/$hotelId'
      fullPath: '/$hotelId/'
      preLoaderRoute: typeof AppHotelIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$hotelId/rooms/page': {
      id: '/_app/$hotelId/rooms/page'
      path: '/$hotelId/rooms/page'
      fullPath: '/$hotelId/rooms/page'
      preLoaderRoute: typeof AppHotelIdRoomsPageRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppHotelIdIndexRoute: typeof AppHotelIdIndexRoute
  AppHotelIdRoomsPageRoute: typeof AppHotelIdRoomsPageRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppHotelIdIndexRoute: AppHotelIdIndexRoute,
  AppHotelIdRoomsPageRoute: AppHotelIdRoomsPageRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
