export {
	type Amenity,
	AmenitySchema,
	type CreateAmenityInput,
	CreateAmenityInputSchema,
	type DeleteAmenityInput,
	DeleteAmenityInputSchema,
	type GetAmenityInput,
	GetAmenityInputSchema,
	type ListAmenitiesInput,
	ListAmenitiesInputSchema,
	type UpdateAmenityInput,
	UpdateAmenityInputSchema,
} from "./features/amenity/amenity.schemas";
export {
	type Contact,
	ContactSchema,
	type CreateContactInput,
	CreateContactInputSchema,
	type GetContactInput,
	GetContactInputSchema,
	type ListContactsByHotelInput,
	ListContactsByHotelInputSchema,
} from "./features/contact/contact.schemas";
export {
	type CreateHotelInput,
	CreateHotelInputSchema,
	type GetHotelInput,
	GetHotelInputSchema,
	type Hotel,
	HotelSchema,
	type ToggleHotelArchivedInput,
	ToggleHotelArchivedInputSchema,
	type UpdateHotelInput,
	UpdateHotelInputSchema,
} from "./features/hotel/hotel.schemas";
